deploy frontend and backend

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -374,70 +374,69 @@ jobs:
       - destroy-environment
       - revert-migrations   
 
-  smoke-test:
-    docker:
-      - image: cimg/base:stable
-    steps:
-      - checkout
+  # smoke-test:
+  #   docker:
+  #     - image: cimg/base:stable
+  #   steps:
+  #     - checkout
+  #     - install_nodejs
+  #     - install_awscli
+  #     - run:
+  #         name: Backend smoke test
+  #         command: |
+  #           BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
+  #             --filter Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7} \
+  #             --query 'Reservations[*].Instances[*].PublicIpAddress' \
+  #             --output test)
+  #             export API_URL=http://${BACKEND_PUBLIC_IP}:3030
+  #             echo ${BACKEND_PUBLIC_IP}
+  #             echo backend-${CIRCLE_WORKFLOW_ID_0:7}
+  #             echo {API_URL}
+  #             if curl -s $API_URL/api/status | grep "ok"
+  #             then
+  #               exit 0
+  #             else
+  #               exit 1
+  #             fi       
+  #     - run:
+  #         name: Frontend smoke test.
+  #         command: |
+  #           FRONTEND_WEBSITE="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com/"            
+  #             echo $FRONTEND_WEBSITE
+  #             if curl -s $FRONTEND_WEBSITE | grep "Welcome"
+  #             then
+  #                 # Change this to 0 after the job fails
+  #               exit 0
+  #             else
+  #               exit 1
+  #             fi
+  #     - destroy-environment
+  #     - revert-migrations 
 
-      - install_nodejs
-      - install_awscli
-      - run:
-          name: Backend smoke test
-          command: |
-            BACKEND_PUBLIC_IP=$(aws ec2 describe-instances \
-              --filter Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7} \
-              --query 'Reservations[*].Instances[*].PublicIpAddress' \
-              --output test)
-              export API_URL=http://${BACKEND_PUBLIC_IP}:3030
-              echo ${BACKEND_PUBLIC_IP}
-              echo backend-${CIRCLE_WORKFLOW_ID_0:7}
-              echo {API_URL}
-              if curl -s $API_URL/api/status | grep "ok"
-              then
-                exit 0
-              else
-                exit 1
-              fi       
-      - run:
-          name: Frontend smoke test.
-          command: |
-            FRONTEND_WEBSITE="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.${AWS_DEFAULT_REGION}.amazonaws.com/"            
-              echo $FRONTEND_WEBSITE
-              if curl -s $FRONTEND_WEBSITE | grep "Welcome"
-              then
-                  # Change this to 0 after the job fails
-                exit 0
-              else
-                exit 1
-              fi
-      - destroy-environment
-      - revert-migrations 
-
-  cloudfront-update:
-    docker:
-      - image: aws/aws-cli
-    steps:
-      # Checkout code from git
-      - checkout
-      - run:
-          name: Install dependencies /Save Old Workflow ID to kvdb.io
-          command: |
-            export OLD_WORKFLOW_ID=$(aws cloudformation \
-            list-exports --query "Export[?=Name==\`WorkflowID\`].Value" \
-            --no-paginate --output text)
-            echo "Old Workflow ID: $OLD_WORKFLOW_ID"
-            curl https://kvdb.io/3uPKwkHBWbwMWo7giejVRd/old_workflow_id -d "${OLD_WORKFLOW_ID"
-      - run:
-          name: Update cloudfront distribution
-          command: |
-            aws cloudformation deploy \
-            --template-file .circleci/files/cloudfont.yml \
-            --parameters-overrides WorkflowID="${CIRCLE_WORKFLOW_ID:0:7}" \
-            --stack-name InitialStack
-      # Here's where you will add some code to rollback on failure  
-      - destroy-environment
-      - revert-migrations
+  # cloudfront-update:
+  #   docker:
+  #     - image: aws/aws-cli
+  #   steps:
+  #     # Checkout code from git
+  #     - checkout
+  #     - run:
+  #         name: Install dependencies /Save Old Workflow ID to kvdb.io
+  #         command: |
+  #           export OLD_WORKFLOW_ID=$(aws cloudformation \
+  #           list-exports --query "Export[?=Name==\`WorkflowID\`].Value" \
+  #           --no-paginate --output text)
+  #           echo "Old Workflow ID: $OLD_WORKFLOW_ID"
+  #           curl https://kvdb.io/3uPKwkHBWbwMWo7giejVRd/old_workflow_id -d "${OLD_WORKFLOW_ID"
+  #     - run:
+  #         name: Update cloudfront distribution
+  #         command: |
+  #           aws cloudformation deploy \
+  #           --template-file .circleci/files/cloudfont.yml \
+  #           --parameters-overrides WorkflowID="${CIRCLE_WORKFLOW_ID:0:7}" \
+  #           --stack-name InitialStack
+  #     # Here's where you will add some code to rollback on failure  
+  #     - destroy-environment
+  #     - revert-migrations
 
 # cleanup:
 #     docker:
@@ -485,8 +484,8 @@ workflows:
           requires: [run-migrations]
       - deploy-backend:
           requires: [run-migrations]
-      - smoke-test:
-          requires: [deploy-backend, deploy-frontend]
+      # - smoke-test:
+      #     requires: [deploy-backend, deploy-frontend]
       # - cloudfront-update:
       #     requires: [smoke-test]
       # - cleanup:
